### ISSUE TITLE
Rename "thread.h" in this project

### ISSUE THREAD

**Issue by Gocy015** [meitu/MTAppenderFile#1]
Hi， 最近在使用 `MTHawkeye`，相当于间接使用到 `MTAppenderFile` 这个库，发现这个工程总有一个 `thread.h` 文件。集成进我们自己的项目，发现会和其它三方库的头文件重名（在我们的工程中，和 ffmpegframework 的 `thread.h` 重名了），导致 xcode 索引错头文件，编译失败。

麻烦修改一下这些头文件，或者是将  include 语句带上文件夹 
```
#include "MTAppenderFile/thread.h"
```

**Comment by euanchan** [comment]
@Gocy015 MTAppenderFile 0.4.1 版本已做了调整
